
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: multiclusterloggingscopes.clusters.verrazzano.io
spec:
  group: clusters.verrazzano.io
  names:
    kind: MultiClusterLoggingScope
    listKind: MultiClusterLoggingScopeList
    plural: multiclusterloggingscopes
    shortNames:
    - mcloggingscope
    - mcloggingscopes
    singular: multiclusterloggingscope
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MultiClusterLoggingScope is the Schema for the multiclusterloggingscopes
          API, which will be used in the management cluster, to create a LoggingScope
          targeted at one or more managed clusters
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MultiClusterLoggingScopeSpec defines the desired state of
              MultiClusterLoggingScope
            properties:
              placement:
                description: Clusters in which the secret is to be placed
                properties:
                  clusters:
                    items:
                      description: Cluster where multi cluster resources are placed
                      properties:
                        name:
                          description: the name of the cluster
                          type: string
                      required:
                      - name
                      type: object
                    type: array
                required:
                - clusters
                type: object
              template:
                description: The embedded LoggingScope
                properties:
                  metadata:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  spec:
                    description: LoggingScopeSpec defines the desired state of LoggingScope
                    properties:
                      elasticSearchHost:
                        description: Host for ElasticSearch
                        type: string
                      elasticSearchPort:
                        description: Port for ElasticSearch
                        format: int32
                        type: integer
                      fluentdImage:
                        description: The fluentd image
                        type: string
                      secretName:
                        description: Name of secret with ElasticSearch credentials
                        type: string
                      workloadRefs:
                        description: WorkloadReferences to the workloads this scope
                          applies to.
                        items:
                          description: A TypedReference refers to an object by Name,
                            Kind, and APIVersion. It is commonly used to reference
                            cluster-scoped objects or objects where the namespace
                            is already known.
                          properties:
                            apiVersion:
                              description: APIVersion of the referenced object.
                              type: string
                            kind:
                              description: Kind of the referenced object.
                              type: string
                            name:
                              description: Name of the referenced object.
                              type: string
                            uid:
                              description: UID of the referenced object.
                              type: string
                          required:
                          - apiVersion
                          - kind
                          - name
                          type: object
                        type: array
                    required:
                    - elasticSearchHost
                    - elasticSearchPort
                    - fluentdImage
                    - secretName
                    - workloadRefs
                    type: object
                type: object
            required:
            - placement
            - template
            type: object
          status:
            description: MultiClusterLoggingScopeStatus defines the observed state
              of MultiClusterLoggingScope
            properties:
              conditions:
                description: The latest available observations of an object's current
                  state.
                items:
                  description: Condition describes current state of a multi cluster
                    resource.
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    message:
                      description: Human readable message indicating details about
                        last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              state:
                description: State of the MultiClusterLoggingScopeStatus custom resource
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
