# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: verrazzanomonitoringinstances.verrazzano.io
spec:
  group: verrazzano.io
  version: v1
  scope: Namespaced
  names:
    kind: VerrazzanoMonitoringInstance
    listKind: VerrazzanoMonitoringInstanceList
    plural: verrazzanomonitoringinstances
    singular: verrazzanomonitoringinstance
    shortNames:
      - vmi
  validation:
    openAPIV3Schema:
      properties:
        metadata:
          properties:
            name:
              type: string
              pattern: '^\w[^._]+$'
              maxLength: 32
            namespace:
              type: string
              pattern: '^\w[^._]+$'
              maxLength: 32
          required:
            - name
            - namespace
        spec:
          properties:
            lock:
              type: boolean
            alertmanager:
              properties:
                config:
                  type: string
                  pattern: '[A-Za-z0-9-_]+'
                configMap:
                  type: string
                  pattern: '^\w[^.]+$'
                enabled:
                  type: boolean
                resources:
                  properties:
                    limitCPU:
                      type: string
                      pattern: '^([1-9]\d*|\d+\.\d{1,2})m?$'
                    limitMemory:
                      type: string
                      pattern: '^[1-9]\d*(Mi|Gi)$'
                    requestCPU:
                      type: string
                      pattern: '^([1-9]\d*|\d+\.\d{1,2})m?$'
                    requestMemory:
                      type: string
                      pattern: '^[1-9]\d*(Mi|Gi)$'
              required:
                - enabled
            api:
              properties:
                replicas:
                  type: number
                  pattern: '\d+'
                resources:
                  properties:
                    limitCPU:
                      type: string
                      pattern: '^([1-9]\d*|\d+\.\d{1,2})m?$'
                    limitMemory:
                      type: string
                      pattern: '^[1-9]\d*(Mi|Gi)$'
                    requestCPU:
                      type: string
                      pattern: '^([1-9]\d*|\d+\.\d{1,2})m?$'
                    requestMemory:
                      type: string
                      pattern: '^[1-9]\d*(Mi|Gi)$'
            elasticsearch:
              properties:
                enabled:
                  type: boolean
                resources:
                  properties:
                    limitCPU:
                      type: string
                      pattern: '^([1-9]\d*|\d+\.\d{1,2})m?$'
                    limitMemory:
                      type: string
                      pattern: '^[1-9]\d*(Mi|Gi)$'
                    requestCPU:
                      type: string
                      pattern: '^([1-9]\d*|\d+\.\d{1,2})m?$'
                    requestMemory:
                      type: string
                      pattern: '^[1-9]\d*(Mi|Gi)$'
                    maxSizeDisk:
                      type: string
                      pattern: '^[1-9]\d*(Mi|Gi)$'
                    minSizeDisk:
                      type: string
                      pattern: '^[1-9]\d*(Mi|Gi)$'
                storage:
                  properties:
                    availabilityDomain:
                      type: string
                      pattern: '^[A-Z]+(-?[A-Z0-9]+)*$'
                    size:
                      type: string
                      pattern: '^[1-9]+\d*(Mi|Gi)$'
                    pvcNames:
                      type: array
                      minItems: 0
                      items:
                        type: string
                        pattern: '[A-Za-z0-9-_]+'
                retentionPeriodDays:
                  type: number
                  pattern: '\d+'
                retentionPeriodMonths:
                  type: number
                  pattern: '\d+'
                openPeriodDays:
                  type: number
                  pattern: '\d+'
                openPeriodMonths:
                  type: number
                  pattern: '\d+'
            grafana:
              properties:
                enabled:
                  type: boolean
                resources:
                  properties:
                    limitCPU:
                      type: string
                      pattern: '^([1-9]\d*|\d+\.\d{1,2})m?$'
                    limitMemory:
                      type: string
                      pattern: '^[1-9]\d*(Mi|Gi)$'
                    requestCPU:
                      type: string
                      pattern: '^([1-9]\d*|\d+\.\d{1,2})m?$'
                    requestMemory:
                      type: string
                      pattern: '^[1-9]\d*(Mi|Gi)$'
                storage:
                  properties:
                    availabilityDomain:
                      type: string
                      pattern: '^[A-Z]+(-?[A-Z0-9]+)*$'
                    size:
                      type: string
                      pattern: '^[1-9]+\d*(Mi|Gi)$'
                    pvcNames:
                      type: array
                      minItems: 0
                      items:
                        type: string
                        pattern: '[A-Za-z0-9-_]+'
                datasourcesConfigMap:
                  type: string
                  pattern: '^\w[^.]+$'
                dashboardsConfigMap:
                  type: string
                  pattern: '^\w[^.]+$'
            kibana:
              properties:
                enabled:
                  type: boolean
                replicas:
                  type: number
                  pattern: '\d+'
                resources:
                  properties:
                    limitCPU:
                      type: string
                      pattern: '^([1-9]\d*|\d+\.\d{1,2})m?$'
                    limitMemory:
                      type: string
                      pattern: '^[1-9]\d*(Mi|Gi)$'
                    requestCPU:
                      type: string
                      pattern: '^([1-9]\d*|\d+\.\d{1,2})m?$'
                    requestMemory:
                      type: string
                      pattern: '^[1-9]\d*(Mi|Gi)$'
            prometheus:
              properties:
                enabled:
                  type: boolean
                resources:
                  properties:
                    limitCPU:
                      type: string
                      pattern: '^([1-9]\d*|\d+\.\d{1,2})m?$'
                    limitMemory:
                      type: string
                      pattern: '^[1-9]\d*(Mi|Gi)$'
                    requestCPU:
                      type: string
                      pattern: '^([1-9]\d*|\d+\.\d{1,2})m?$'
                    requestMemory:
                      type: string
                      pattern: '^[1-9]\d*(Mi|Gi)$'
                    maxSizeDisk:
                      type: string
                      pattern: '^[1-9]\d*(Mi|Gi)$'
                    minSizeDisk:
                      type: string
                      pattern: '^[1-9]\d*(Mi|Gi)$'
                storage:
                  properties:
                    availabilityDomain:
                      type: string
                      pattern: '^[A-Z]+(-?[A-Z0-9]+)*$'
                    size:
                      type: string
                      pattern: '^[1-9]+\d*(Mi|Gi)$'
                    pvcNames:
                      type: array
                      minItems: 0
                      items:
                        type: string
                        pattern: '[A-Za-z0-9-_]+'
                config:
                  type: string
                  pattern: '[A-Za-z0-9-_]+'
                rulesConfig:
                  type: string
                  pattern: '[A-Za-z0-9-_]+'
                retentionPeriod:
                  type: number
                  pattern: '\d+'
            prometheusGW:
              properties:
                configMap:
                  type: string
                  pattern: '^\w[^.]+$'
                resources:
                  properties:
                    limitCPU:
                      type: string
                      pattern: '^([1-9]\d*|\d+\.\d{1,2})m?$'
                    limitMemory:
                      type: string
                      pattern: '^[1-9]\d*(Mi|Gi)$'
                    requestCPU:
                      type: string
                      pattern: '^([1-9]\d*|\d+\.\d{1,2})m?$'
                    requestMemory:
                      type: string
                      pattern: '^[1-9]\d*(Mi|Gi)$'
                maintenanceSchedule:
                  type: string
            autoSecret:
              type: boolean
            secretsName:
              type: string
              pattern: '^\w[^.]+$'
            ingresstargetdnsname:
              type: string
              pattern: '[a-z]+[a-z0-9-.]*'
            preserveOnDelete:
              type: boolean
            uri:
              type: string
              pattern: '[A-Za-z0-9-_]+'
            externalSiteMonitor:
              properties:
                providers:
                  type: array
                  items:
                    type: string
                    pattern: '[A-Za-z0-9-_]+'
                alertContact:
                  type: string
                  pattern: '[A-Za-z0-9-_]+'
                alertThresholdMinutes:
                  type: number
                alertRecurrenceMinutes:
                  type: number
                ignoreSSLErrors:
                  type: boolean
                monitorIntervalSeconds:
                  type: number
                basicAuthSecretName:
                  type: number
            pagerduty:
              properties:
                id:
                  type: string
                  pattern: '[A-Za-z0-9]+'
            bastille:
              properties:
                url:
                  type: array
                  items:
                    type: string
                    pattern: '^(http(s?)://)?((\w+\.)?\w+\.\w+|((2[0-5]{2}|1[0-9]{2}|[0-9]{1,2})\.){3}(2[0-5]{2}|1[0-9]{2}|[0-9]{1,2})(:[1-9]\d*)?)(/)?$'
            slack:
              properties:
                id:
                  type: string
                  pattern: '[A-Za-z0-9-_]+'
                url:
                  type: string
                  pattern: '^(http(s?)://)?((\w+\.)?\w+\.\w+|((2[0-5]{2}|1[0-9]{2}|[0-9]{1,2})\.){3}(2[0-5]{2}|1[0-9]{2}|[0-9]{1,2})(:[1-9]\d*)?)(/)?$'
            serviceType:
              type: string
              pattern: '[A-Za-z0-9-_]+'
            versioning:
              properties:
                currentVersion:
                  type: string
                  pattern: '[A-Za-z0-9-_]+'
                desiredVersion:
                  type: string
                  pattern: '[A-Za-z0-9-_]+'
      required:
        - metadata
        - spec
---
