# Copyright (c) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.verrazzanoAdmissionController.name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.verrazzanoAdmissionController.name }}
rules:
  - apiGroups:
      - verrazzano.io
    resources:
      - verrazzanobindings
      - verrazzanomanagedclusters
      - verrazzanomodels
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - namespaces
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.verrazzanoAdmissionController.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.verrazzanoAdmissionController.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.verrazzanoAdmissionController.name }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.verrazzanoAdmissionController.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Values.verrazzanoAdmissionController.name }}
spec:
  ports:
    - name: webhook
      port: 443
      targetPort: 8080
  selector:
    name: {{ .Values.verrazzanoAdmissionController.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.verrazzanoAdmissionController.controllerName }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Values.verrazzanoAdmissionController.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.verrazzanoAdmissionController.name }}
  template:
    metadata:
      name: {{ .Values.verrazzanoAdmissionController.controllerName }}
      labels:
        name: {{ .Values.verrazzanoAdmissionController.name }}
    spec:
      containers:
        - name: webhook
          image: {{ .Values.verrazzanoAdmissionController.imageName }}:{{ .Values.verrazzanoAdmissionController.imageVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --v=4
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ .Values.verrazzanoAdmissionController.name }}
      serviceAccount: {{ .Values.verrazzanoAdmissionController.name }}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.verrazzanoAdmissionController.name }}
webhooks:
  - name: verrazzano-validation.oracle.com
    clientConfig:
      service:
        name: {{ .Values.verrazzanoAdmissionController.name }}
        namespace: {{ .Release.Namespace }}
        path: "/validate"
      caBundle: {{ b64enc .Values.verrazzanoAdmissionController.caBundle }}
    rules:
      - resources: ["verrazzanobindings"]
        apiGroups: ["verrazzano.io"]
        apiVersions: ["v1beta1"]
        operations: ["CREATE","UPDATE"]
      - resources: ["verrazzanomodels"]
        apiGroups: ["verrazzano.io"]
        apiVersions: ["v1beta1"]
        operations: ["CREATE","UPDATE","DELETE"]
    sideEffects: None
    failurePolicy: Fail
