# Copyright (c) 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.logging.name }}-es-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.logging.name }}
data:
  es-url: {{ .Values.logging.osURL }}
  es-secret: {{ .Values.logging.credentialsSecret }}

