# Copyright (c) 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
# This install resource uses the "managed-cluster" profile to install reduced footprint 
# Verrazzano for managed clusters.
#
# In a "managed-cluster" install the following services are excluded:
#
# - Elasticsearch
# - Kibana
# - Grafana
#
# Prometheus is installed for recording metrics from the system services and deployed apps in the local
# cluster, which will then be scraped from the admin cluster.
#
apiVersion: install.verrazzano.io/v1alpha1
kind: Verrazzano
metadata:
  name: my-verrazzano-managed-cluster
spec:
  profile: managed-cluster
