# Copyright (c) 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

ID: prom-s1
name: prometheus-s1
description: |
  This is a scenario that receives alerts from Prometheus and generates events
usecases:
  - usecasePath: prometheus/alerts.yaml
    overrideFile: alerts.yaml
