# Copyright (c) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/install.verrazzano.io_verrazzanos.yaml
- bases/clusters.verrazzano.io_verrazzanomanagedclusters.yaml
# +kubebuilder:scaffold:crdkustomizeresource
