# Copyright (c) 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
spec:
  components:
    keycloak:
      enabled: false
    rancher:
      enabled: false
    opensearch:
      enabled: false
    grafana:
      enabled: false
    opensearchDashboards:
      enabled: false
    console:
      enabled: false
    kiali:
      enabled: false
