apiVersion: v1
appVersion: 0.7.0
deprecated: true
description: DEPRECATED ExternalDNS is a Kubernetes addon that configures public DNS
  servers with information about exposed Kubernetes services to make them discoverable.
engine: gotpl
home: https://github.com/kubernetes-sigs/external-dns
icon: https://bitnami.com/assets/stacks/external-dns/img/external-dns-stack-110x117.png
keywords:
- external-dns
- network
- dns
name: external-dns
sources:
- https://github.com/kubernetes-sigs/external-dns
- https://github.com/bitnami/bitnami-docker-external-dns
version: 2.20.4
