# Copyright (c) 2022, 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

image:
  pullPolicy: IfNotPresent
podAnnotations:
  traffic.sidecar.istio.io/excludeOutboundPorts: "443"
restic:
  annotations:
    traffic.sidecar.istio.io/excludeOutboundPorts: "443"
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
      add: ["NET_BIND_SERVICE"]
    readOnlyRootFilesystem: false
metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus-operator
configuration:
  provider: aws
backupsEnabled: false
cleanUpCRDs: false
credentials:
  useSecret: false
deployRestic: true
snapshotsEnabled: false
upgradeCRDs: false
configMaps:
  restic-restore-action-config:
    labels:
      velero.io/plugin-config: ""
      velero.io/restic: RestoreItemAction
podSecurityContext:
  runAsGroup: 65534
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
    add: ["NET_BIND_SERVICE"]
  readOnlyRootFilesystem: true
  privileged: false