# Copyright (c) 2021, 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

# NOTE: The image you're looking for isn't here. The WKO image now comes from
# the bill of materials file (verrazzano-bom.json).

annotations:
    traffic.sidecar.istio.io/excludeOutboundPorts: "443"


# TEST
image: phx.ocir.io/weblogick8s/weblogic-kubernetes-operator:diagnose-wme
