# Copyright (c) 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
apiVersion: v1
description: A Helm chart for Verrazzano Fluentd
name: fluentd
version: 1.5.0
appVersion: 1.5.0
