# Copyright (c) 2023, Oracle and/or its affiliates.
# # Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

global:
  envVars:
    DOMAIN_UID: bobbys-front-end
    DOMAIN_NAMESPACE: bobs-books
