# Copyright (c) 2021, 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: verrazzanoweblogicworkloads.oam.verrazzano.io
spec:
  childResourceKinds:
    - apiVersion: weblogic.oracle/v8
      kind: Domain
    - apiVersion: weblogic.oracle/v9
      kind: Domain
    - apiVersion: weblogic.oracle/v1
      kind: Cluster
  definitionRef:
    name: verrazzanoweblogicworkloads.oam.verrazzano.io
