# Copyright (c) 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

controller:
  image:
    repository: ghcr.io/verrazzano/nginx-ingress-controller
    tag: 0.32-20201016205412-8580ea0ef
  config:
    client-body-buffer-size: 64k
  metrics:
    enabled: true
  publishService:
    enabled: true
  service:
    enableHttp: false
  podAnnotations:
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
    system.io/scrape: "true"
defaultBackend:
  image:
    repository: ghcr.io/verrazzano/nginx-ingress-default-backend
    tag: 0.32-20201016205412-8580ea0ef
