# Copyright (c) 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
spec:
  defaultVolumeSource:
    emptyDir: { }
  components:
    elasticsearch:
      nodes:
        - name: es-master
          replicas: 1
          resources:
            requests:
              memory: 1G
          roles:
            - master
