# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
name: verrazzano

# Development profile
# - single-node ES cluster
# - with no persistent storage for ES, Prometheus, or Grafana

verrazzanoOperator:
  prometheusDataStorageSize: ""
  grafanaDataStorageSize: ""
  esDataStorageSize: ""

elasticSearch:
  nodes:
    master:
      replicas: 1
      requests:
        memory: 1Gi
    data:
      replicas: 0
    ingest:
      replicas: 0
