# Copyright (c) 2021, 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
spec:
  environmentName: default
  components:
    applicationOperator:
      enabled: true
    authProxy:
      enabled: true
      kubernetes:
        replicas: 1
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - verrazzano-authproxy
                  topologyKey: kubernetes.io/hostname
    certManager:
      enabled: true
      certificate:
        ca:
          secretName: "verrazzano-ca-certificate-secret"
          clusterResourceNamespace: "cert-manager"
      overrides:
        - values:
            replicaCount: 1
            affinity:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - podAffinityTerm:
                      labelSelector:
                        matchLabels:
                          app: cert-manager
                      topologyKey: kubernetes.io/hostname
                    weight: 100
            cainjector:
              replicaCount: 1
              affinity:
                podAntiAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                    - podAffinityTerm:
                        labelSelector:
                          matchLabels:
                            app: cainjector
                        topologyKey: kubernetes.io/hostname
                      weight: 100
            webhook:
              replicaCount: 1
              affinity:
                podAntiAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                    - podAffinityTerm:
                        labelSelector:
                          matchLabels:
                            app: webhook
                        topologyKey: kubernetes.io/hostname
                      weight: 100
    coherenceOperator:
      enabled: true
    console:
      enabled: true
      overrides:
        - values:
            replicas: 1
            affinity:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - podAffinityTerm:
                      labelSelector:
                        matchLabels:
                          app: verrazzano-console
                      topologyKey: kubernetes.io/hostname
                    weight: 100
    dns:
      wildcard:
        domain: "nip.io"
    elasticsearch:
      enabled: true
    fluentd:
      enabled: true
      elasticsearchURL: "http://verrazzano-authproxy-elasticsearch:8775"
      elasticsearchSecret: verrazzano-es-internal
    grafana:
      enabled: true
    ingress:
      enabled: true
      type: LoadBalancer
      overrides:
        - values:
            controller:
              autoscaling:
                enabled: false
                minReplicas: 1
              affinity:
                podAntiAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                    - podAffinityTerm:
                        labelSelector:
                          matchLabels:
                            app.kubernetes.io/component: controller
                            app.kubernetes.io/name: ingress-nginx
                        topologyKey: kubernetes.io/hostname
                      weight: 100
            defaultBackend:
              replicaCount: 1
              affinity:
                podAntiAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                    - podAffinityTerm:
                        labelSelector:
                          matchLabels:
                            app.kubernetes.io/component: default-backend
                            app.kubernetes.io/name: ingress-nginx
                        topologyKey: kubernetes.io/hostname
                      weight: 100
    istio:
      enabled: true
      overrides:
        - values:
            apiVersion: install.istio.io/v1alpha1
            kind: IstioOperator
            spec:
              values:
                meshConfig:
                  defaultConfig:
                    tracing:
                      tlsSettings:
                        mode: ISTIO_MUTUAL
                      zipkin:
                        address: jaeger-operator-jaeger-collector.verrazzano-monitoring.svc.cluster.local.:9411
              components:
                pilot:
                  k8s:
                    affinity:
                      podAntiAffinity:
                        preferredDuringSchedulingIgnoredDuringExecution:
                          - podAffinityTerm:
                              labelSelector:
                                matchLabels:
                                  app: istiod
                              topologyKey: kubernetes.io/hostname
                            weight: 100
                egressGateways:
                  - enabled: true
                    k8s:
                      affinity:
                        podAntiAffinity:
                          preferredDuringSchedulingIgnoredDuringExecution:
                            - podAffinityTerm:
                                labelSelector:
                                  matchExpressions:
                                    - key: app
                                      operator: In
                                      values:
                                        - istio-egressgateway
                                topologyKey: kubernetes.io/hostname
                              weight: 100
                      replicaCount: 1
                    name: istio-egressgateway
                ingressGateways:
                  - enabled: true
                    k8s:
                      affinity:
                        podAntiAffinity:
                          preferredDuringSchedulingIgnoredDuringExecution:
                            - podAffinityTerm:
                                labelSelector:
                                  matchExpressions:
                                    - key: app
                                      operator: In
                                      values:
                                        - istio-ingressgateway
                                topologyKey: kubernetes.io/hostname
                              weight: 100
                      replicaCount: 1
                      service:
                        type: LoadBalancer
                    name: istio-ingressgateway

    kiali:
      enabled: true
      overrides:
        - values:
            deployment:
              replicas: 1
              affinity:
                pod_anti:
                  preferredDuringSchedulingIgnoredDuringExecution:
                    - podAffinityTerm:
                        labelSelector:
                          matchLabels:
                            app: kiali
                        topologyKey: kubernetes.io/hostname
                      weight: 100
    keycloak:
      enabled: true
      overrides:
        - values:
            replicas: 1
            affinity: |
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      labelSelector:
                        matchLabels:
                          app.kubernetes.io/instance: keycloak
                          app.kubernetes.io/name: keycloak
                      topologyKey: kubernetes.io/hostname
    mySQLOperator:
      enabled: true
    kibana:
      enabled: true
      replicas: 1
    oam:
      enabled: true
    prometheus:
      enabled: true
    prometheusOperator:
      enabled: true
      overrides:
        - values:
            prometheus:
              prometheusSpec:
                replicas: 1
                affinity:
                  podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                      - podAffinityTerm:
                          labelSelector:
                            matchLabels:
                              app.kubernetes.io/name: prometheus
                          topologyKey: kubernetes.io/hostname
                        weight: 100
    rancher:
      enabled: true
    verrazzano:
      enabled: true
    weblogicOperator:
      enabled: true
