# Copyright (c) 2021, 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

spec:
  components:
    elasticsearch:
      nodes:
        - name: es-master
          replicas: 3
          storage:
            size: 50Gi
          resources:
            requests:
              memory: 1.4Gi
          roles:
            - master
        - name: es-data
          replicas: 3
          storage:
            size: 50Gi
          roles:
            - data
          resources:
            requests:
              memory: 4.8Gi
        - name: es-ingest
          replicas: 1
          resources:
            requests:
              memory: 2.5Gi
          roles:
            - ingest
      enabled: true
    certManager:
      enabled: true
      certificate:
        ca:
          secretName: "verrazzano-ca-certificate-secret"
          clusterResourceNamespace: "cert-manager"
    prometheusOperator:
      overrides:
        - values:
            prometheus:
              prometheusSpec:
                resources:
                  requests:
                    memory: "128Mi"

    argocd:
      enabled: true
