# Copyright (c) 2021, 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: multiclusterconfigmaps.clusters.verrazzano.io
spec:
  group: clusters.verrazzano.io
  names:
    kind: MultiClusterConfigMap
    listKind: MultiClusterConfigMapList
    plural: multiclusterconfigmaps
    shortNames:
    - mccm
    - mccms
    singular: multiclusterconfigmap
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MultiClusterConfigMap specifies the Multi Cluster ConfigMap API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: The desired state of a Multi Cluster ConfigMap resource.
            properties:
              placement:
                description: Clusters in which the config map is to be created.
                properties:
                  clusters:
                    items:
                      description: Cluster where multi cluster resources are placed
                      properties:
                        name:
                          description: the name of the cluster
                          type: string
                      required:
                      - name
                      type: object
                    type: array
                required:
                - clusters
                type: object
              template:
                description: The embedded Kubernetes config map.
                properties:
                  binaryData:
                    additionalProperties:
                      format: byte
                      type: string
                    description: Corresponds to the `binaryData` field of the `struct`
                      ConfigMap defined in <a href="https://github.com/kubernetes/api/blob/master/core/v1/types.go">types.go</a>.
                    type: object
                  data:
                    additionalProperties:
                      type: string
                    description: Corresponds to the `data` field of the `struct` ConfigMap
                      defined in <a href="https://github.com/kubernetes/api/blob/master/core/v1/types.go">types.go</a>.
                    type: object
                  immutable:
                    description: Corresponds to the `immutable` field of the `struct`
                      ConfigMap defined in <a href="https://github.com/kubernetes/api/blob/master/core/v1/types.go">types.go</a>.
                    type: boolean
                  metadata:
                    description: Metadata describing the config map.
                    properties:
                      annotations:
                        additionalProperties:
                          type: string
                        description: Annotations is an unstructured key value map
                          stored with a resource that may be set by external tools
                          to store and retrieve arbitrary metadata.
                        type: object
                      labels:
                        additionalProperties:
                          type: string
                        description: Map of string keys and values that can be used
                          to organize and categorize (scope and select) objects.
                        type: object
                      name:
                        description: Name must be unique within a namespace.
                        type: string
                      namespace:
                        description: Namespace defines the space within each name
                          must be unique.
                        type: string
                    type: object
                type: object
            required:
            - placement
            - template
            type: object
          status:
            description: The observed state of a Multi Cluster ConfigMap resource.
            properties:
              clusters:
                items:
                  description: ClusterLevelStatus describes the status of the multi
                    cluster resource in a specific cluster
                  properties:
                    lastUpdateTime:
                      description: LastUpdateTime of the resource state in this cluster
                      type: string
                    message:
                      description: Message with details about the status in this cluster
                      type: string
                    name:
                      description: Name of the cluster
                      type: string
                    state:
                      description: State of the resource in this cluster
                      type: string
                  required:
                  - lastUpdateTime
                  - name
                  - state
                  type: object
                type: array
              conditions:
                description: The latest available observations of an object's current
                  state.
                items:
                  description: Condition describes current state of a multi cluster
                    resource.
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    message:
                      description: Human readable message indicating details about
                        last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              state:
                description: State of the multi cluster resource
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
