# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: metricstraits.oam.verrazzano.io
spec:
  group: oam.verrazzano.io
  names:
    kind: MetricsTrait
    listKind: MetricsTraitList
    plural: metricstraits
    singular: metricstrait
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MetricsTrait specifies the metrics trait API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MetricsTraitSpec specifies the desired state of a metrics
              trait.
            properties:
              enabled:
                description: Specifies whether metrics collection is enabled. Defaults
                  to `true`.
                type: boolean
              path:
                description: The HTTP path for the related metrics endpoint. Defaults
                  to `/metrics`.
                type: string
              port:
                description: The HTTP port for the related metrics trait. Defaults
                  to `8080`.
                type: integer
              ports:
                description: The HTTP ports for the related metrics trait. Defaults
                  to `8080`.
                items:
                  description: PortSpec defines an HTTP port and path combination
                  properties:
                    path:
                      description: The HTTP path for the related metrics endpoint.
                        Defaults to `/metrics`.
                      type: string
                    port:
                      description: The HTTP port for the related metrics trait. Defaults
                        to `8080`.
                      type: integer
                  type: object
                type: array
              scraper:
                description: The Prometheus deployment used to scrape the related
                  metrics endpoints. By default, the Verrazzano-supplied Prometheus
                  component is used to scrape the endpoint.
                type: string
              secret:
                description: The name of an opaque secret (for example, username and
                  password) within the workloadâ€™s namespace for metrics endpoint access.
                type: string
              workloadRef:
                description: The WorkloadReference of the workload to which this trait
                  applies. This value is populated by the OAM runtime when an ApplicationConfiguration
                  resource is processed.  When the ApplicationConfiguration is processed,
                  a trait and a workload resource are created from the content of
                  the ApplicationConfiguration. The WorkloadReference is provided
                  in the trait by OAM to ensure that the trait controller can find
                  the workload associated with the component containing the trait
                  within the original ApplicationConfiguration.
                properties:
                  apiVersion:
                    description: APIVersion of the referenced object.
                    type: string
                  kind:
                    description: Kind of the referenced object.
                    type: string
                  name:
                    description: Name of the referenced object.
                    type: string
                  uid:
                    description: UID of the referenced object.
                    type: string
                required:
                - apiVersion
                - kind
                - name
                type: object
            required:
            - workloadRef
            type: object
          status:
            description: The observed state of a metrics trait and related resources.
            properties:
              conditions:
                description: Conditions of the resource.
                items:
                  description: A Condition that may apply to a resource.
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the last time this condition
                        transitioned from one status to another.
                      format: date-time
                      type: string
                    message:
                      description: A Message containing details about this condition's
                        last transition from one status to another, if any.
                      type: string
                    reason:
                      description: A Reason for this condition's last transition from
                        one status to another.
                      type: string
                    status:
                      description: Status of this condition; is it currently True,
                        False, or Unknown?
                      type: string
                    type:
                      description: Type of this condition. At most one of each condition
                        type may apply to a resource at any point in time.
                      type: string
                  required:
                  - lastTransitionTime
                  - reason
                  - status
                  - type
                  type: object
                type: array
              resources:
                description: Related resources affected by this metrics trait.
                items:
                  description: QualifiedResourceRelation identifies a specific related
                    resource (both APIVersion/Kind and namespace name) along this
                    the role of the resource in the relationship.
                  properties:
                    apiversion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                    role:
                      type: string
                  required:
                  - apiversion
                  - kind
                  - name
                  - namespace
                  - role
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
