# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.verrazzanoOperator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.verrazzanoOperator.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.verrazzanoOperator.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.verrazzanoOperator.name }}
    spec:
      containers:
        - name: {{ .Values.verrazzanoOperator.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: {{ .Values.verrazzanoOperator.imageName }}:{{ .Values.verrazzanoOperator.imageVersion }}
          args:
            - --zap-log-level=info
            - --zap-devel=false
            - --verrazzanoUri={{ .Values.config.envName }}.{{ .Values.config.dnsSuffix }}
            - --enableMonitoringStorage={{ .Values.config.enableMonitoringStorage }}
            - --apiServerRealm={{ .Values.verrazzanoOperator.apiServerRealm }}
          resources:
            requests:
              memory: {{ .Values.verrazzanoOperator.RequestMemory }}
          env:
            - name: rancherURL
              value: {{ .Values.clusterOperator.rancherURL }}
            - name: rancherHost
              value: {{ .Values.clusterOperator.rancherHostname }}
            - name: rancherPort
              value: {{ .Values.clusterOperator.rancherHostPort | quote }}
            - name: USE_SYSTEM_VMI
              value: {{ .Values.appBinding.useSystemVMI | quote }}
            - name: PROMETHEUS_PUSHER_IMAGE
              value: {{ .Values.verrazzanoOperator.prometheusPusherImage }}
            - name: NODE_EXPORTER_IMAGE
              value: {{ .Values.verrazzanoOperator.nodeExporterImage }}
            - name: FILEBEAT_IMAGE
              value: {{ .Values.verrazzanoOperator.filebeatImage }}
            - name: JOURNALBEAT_IMAGE
              value: {{ .Values.verrazzanoOperator.journalbeatImage }}
            - name: FLUENTD_IMAGE
              value: {{ .Values.verrazzanoOperator.fluentdImage }}
            - name: ES_MASTER_NODE_REQUEST_MEMORY
              value: {{ .Values.elasticSearch.nodes.master.requests.memory }}
            - name: ES_INGEST_NODE_REQUEST_MEMORY
              value: {{ .Values.elasticSearch.nodes.ingest.requests.memory }}
            - name: ES_DATA_NODE_REQUEST_MEMORY
              value: {{ .Values.elasticSearch.nodes.data.requests.memory }}
            - name: GRAFANA_REQUEST_MEMORY
              value: {{ .Values.verrazzanoOperator.grafanaRequestMemory }}
            - name: GRAFANA_DATA_STORAGE
              value: {{ .Values.verrazzanoOperator.grafanaDataStorageSize }}
            - name: PROMETHEUS_REQUEST_MEMORY
              value: {{ .Values.verrazzanoOperator.prometheusRequestMemory }}
            - name: PROMETHEUS_DATA_STORAGE
              value: {{ .Values.verrazzanoOperator.prometheusDataStorageSize }}
            - name: KIBANA_REQUEST_MEMORY
              value: {{ .Values.verrazzanoOperator.kibanaRequestMemory }}
            - name: ES_MASTER_NODE_REPLICAS
              value: {{ .Values.elasticSearch.nodes.master.replicas | quote }}
            - name: ES_DATA_NODE_REPLICAS
              value: {{ .Values.elasticSearch.nodes.data.replicas | quote }}
            - name: ES_INGEST_NODE_REPLICAS
              value: {{ .Values.elasticSearch.nodes.ingest.replicas | quote }}
            - name: ES_DATA_STORAGE
              value: {{ .Values.verrazzanoOperator.esDataStorageSize }}
      serviceAccount: {{ .Values.verrazzanoOperator.name }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.verrazzanoOperator.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.verrazzanoOperator.name }}
  type: ClusterIP
  ports:
    - name: api
      protocol: TCP
      port: 3456
      targetPort: 3456
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.verrazzanoOperator.name }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.verrazzanoOperator.name }}
rules:
  - apiGroups:
      - verrazzano.io
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - verrazzano.io
    resources:
      - verrazzanomonitoringinstances
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - configmaps
      - endpoints
      - events
      - namespaces
      - persistentvolumeclaims
      - secrets
      - services
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - daemonsets
      - nodes
      - serviceaccounts
      - pods/log
      - pods/portforward
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - patch
      - deletecollection
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - system-node-exporter
    verbs:
      - use
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - delete
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - delete
  - apiGroups:
      - networking.istio.io
    resources:
      - gateways
      - virtualservices
      - serviceentries
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - delete
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - patch
      - deletecollection
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - nonResourceURLs:
      - /version/*
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.verrazzanoOperator.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.verrazzanoOperator.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.verrazzanoOperator.name }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzano-system-read
  labels:
    verrazzano.io/aggregate-to-verrazzano-admin: "true"
    verrazzano.io/aggregate-to-verrazzano-monitor: "true"
rules:
- apiGroups:
    - verrazzano.io
    - oam.verrazzano.io
    - install.verrazzano.io
  resources:
    - "*"
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzano-system-write
  labels:
    verrazzano.io/aggregate-to-verrazzano-admin: "true"
rules:
- apiGroups:
    - verrazzano.io
    - oam.verrazzano.io
    - install.verrazzano.io
  resources:
    - "*"
  verbs:
    - put
    - post
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzano-application-read
  labels:
    verrazzano.io/aggregate-to-verrazzano-admin: "true"
    verrazzano.io/aggregate-to-verrazzano-monitor: "true"
    verrazzano.io/aggregate-to-verrazzano-project-admin: "true"
    verrazzano.io/aggregate-to-verrazzano-project-monitor: "true"
rules:
- apiGroups:
    - verrazzano.io
    - oam.verrazzano.io
    - install.verrazzano.io
  resources:
    - "*"
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzano-application-write
  labels:
    verrazzano.io/aggregate-to-verrazzano-admin: "true"
    verrazzano.io/aggregate-to-verrazzano-project-admin: "true"
rules:
- apiGroups:
    - verrazzano.io
    - oam.verrazzano.io
    - install.verrazzano.io
    - core.oam.dev
  resources:
    - "*"
  verbs:
    - put
    - post
    - create
    - update
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzano-admin
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      verrazzano.io/aggregate-to-verrazzano-admin: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: verrazzano-admin
subjects:
- kind: {{ .Values.userrolebindings.admin.kind }}
  name: {{ .Values.userrolebindings.admin.name }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: verrazzano-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzano-monitor
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      verrazzano.io/aggregate-to-verrazzano-monitor: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: verrazzano-monitor
subjects:
- kind: {{ .Values.userrolebindings.monitor.kind }}
  name: {{ .Values.userrolebindings.monitor.name }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: verrazzano-monitor
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzano-project-admin
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      verrazzano.io/aggregate-to-verrazzano-project-admin: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzano-project-monitor
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      verrazzano.io/aggregate-to-verrazzano-project-monitor: "true"
rules: []
