# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzano-install
  labels:
    verrazzano.io/aggregate-to-verrazzano-admin: "true"
rules:
  - apiGroups:
      - install.verrazzano.io
    resources:
      - "*"
      - "*/status"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - install.verrazzano.io
    resources:
      - "*"
    verbs:
      - create
      - update
      - patch
      - delete
      - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzano-system-read
  labels:
    verrazzano.io/aggregate-to-verrazzano-admin: "true"
    verrazzano.io/aggregate-to-verrazzano-monitor: "true"
rules:
  - apiGroups:
      - clusters.verrazzano.io
      - images.verrazzano.io
    resources:
      - "*"
      - "*/status"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.istio.io
      - networking.istio.io
      - security.istio.io
    resources:
      - "*"
      - "*/status"
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzano-system-write
  labels:
    verrazzano.io/aggregate-to-verrazzano-admin: "true"
rules:
  - apiGroups:
      - clusters.verrazzano.io
      - images.verrazzano.io
    resources:
      - "*"
    verbs:
      - create
      - update
      - patch
      - delete
      - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzano-application-read
  labels:
    verrazzano.io/aggregate-to-verrazzano-admin: "true"
    verrazzano.io/aggregate-to-verrazzano-monitor: "true"
    verrazzano.io/aggregate-to-verrazzano-project-admin: "true"
    verrazzano.io/aggregate-to-verrazzano-project-monitor: "true"
rules:
  - apiGroups:
      - verrazzano.io
      - oam.verrazzano.io
      - core.oam.dev
    resources:
      - "*"
      - "*/status"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - weblogic.oracle
    resources:
      - domains
      - domains/status
      - clusters
      - clusters/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coherence.oracle.com
    resources:
      - coherence
      - coherence/status
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzano-application-write
  labels:
    verrazzano.io/aggregate-to-verrazzano-admin: "true"
    verrazzano.io/aggregate-to-verrazzano-project-admin: "true"
rules:
  - apiGroups:
      - verrazzano.io
      - oam.verrazzano.io
      - core.oam.dev
    resources:
      - "*"
    verbs:
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - weblogic.oracle
    resources:
      - domains
    verbs:
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - coherence.oracle.com
    resources:
      - coherence
    verbs:
      - create
      - update
      - patch
      - delete
      - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzano-admin
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        verrazzano.io/aggregate-to-verrazzano-admin: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: verrazzano-admin
subjects:
  {{- range .Values.security.adminSubjects }}
  - kind: {{ .kind }}
    name: {{ .name }}
    {{- if .namespace }}
    namespace: {{ .namespace }}
    {{- end }}
    {{- if .apiGroup }}
    apiGroup: {{ .apiGroup }}
  {{- end }}
  {{- end }}
roleRef:
  kind: ClusterRole
  name: verrazzano-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: verrazzano-admin-k8s
subjects:
  {{- range .Values.security.adminSubjects }}
  - kind: {{ .kind }}
    name: {{ .name }}
    {{- if .namespace }}
    namespace: {{ .namespace }}
    {{- end }}
    {{- if .apiGroup }}
    apiGroup: {{ .apiGroup }}
  {{- end }}
  {{- end }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzano-monitor
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        verrazzano.io/aggregate-to-verrazzano-monitor: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: verrazzano-monitor
subjects:
  {{- range .Values.security.monitorSubjects }}
  - kind: {{ .kind }}
    name: {{ .name }}
    {{- if .namespace }}
    namespace: {{ .namespace }}
    {{- end }}
    {{- if .apiGroup }}
    apiGroup: {{ .apiGroup }}
  {{- end }}
  {{- end }}
roleRef:
  kind: ClusterRole
  name: verrazzano-monitor
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: verrazzano-monitor-k8s
subjects:
  {{- range .Values.security.monitorSubjects }}
  - kind: {{ .kind }}
    name: {{ .name }}
    {{- if .namespace }}
    namespace: {{ .namespace }}
    {{- end }}
    {{- if .apiGroup }}
    apiGroup: {{ .apiGroup }}
  {{- end }}
  {{- end }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzano-project-admin
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        verrazzano.io/aggregate-to-verrazzano-project-admin: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzano-project-monitor
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        verrazzano.io/aggregate-to-verrazzano-project-monitor: "true"
rules: []
